export const BankNames = [
  'State Bank of Pakistan',
  'National Bank of Pakistan',
  'Habib Bank Limited',
  'United Bank Limited',
  'MCB Bank Limited',
  'Allied Bank Limited',
  'Askari Bank Limited',
  'Meezan Bank',
  'Bank Alfalah',
  'Faysal Bank',
  'Standard Chartered Bank Pakistan',
  'Habib Metropolitan Bank',
  'Bank Islami Pakistan Limited',
  'JS Bank Limited',
  'Bank of Punjab',
  'Summit Bank',
  'Soneri Bank Limited',
  'Sindh Bank Limited',
  'First Women Bank Limited',
  'The Bank of Khyber',
  'Zarai Taraqiati Bank Limited',
  'Bank Al-Habib Limited',
  'Khushhali Bank',
  'NRSP Microfinance Bank',
  'Telenor Microfinance Bank',
  'FINCA Microfinance Bank',
  'U Microfinance Bank'
]
